### ISSUE TITLE
File field required on edit page

### ISSUE THREAD

**Issue by fabienheureux** [takeflight/wagtailvideos#17]
Hi,

If I want to edit a video, the title for example, I am asked to select a file as the file input is marked as required.
Shouldn't it be optionnal on the edit page ? As we may only want to change the title or upload a thumbnail.

Thanks !

**Comment by fabienheureux** [comment]
Didn't all

**Comment by timheap** [comment]
A fix for this issue has been published in [version 0.3.1 on PyPI](https://pypi.python.org/pypi/wagtailvideos/0.3.1)

**Comment by fabienheureux** [comment]
Hi, sorry for the weird message above (and the closed action ?), really don't how it came up. Anyway, thanks a lot the this commit :)
