### ISSUE TITLE
Not compatible with Wagtail > 2

### ISSUE THREAD

**Issue by Premitium** [takeflight/wagtailvideos#25]
I just tried to use the app in a Wagtail project running 2.1 and I get:

from wagtail.wagtailadmin.edit_handlers import BaseChooserPanel
ModuleNotFoundError: No module named 'wagtail.wagtailadmin'

**Comment by SableWalnut** [comment]
Hopefully Wagtail 2.x support will be added very soon! Check out #23! 👍
